#
# Makefile for the kernel dual port ram.
#

obj-$(CONFIG_ANDROID_DEV_DEBUG)			+= android_dev_debug.o
obj-$(CONFIG_YULONG_DEBUG)			+= uart-switch.o
obj-$(CONFIG_YULONG_MODULE_MANAGEMENT)		+= yulong_module_management.o
