#
# Makefile for sensors devices
#

obj-$(CONFIG_SENSORS_AKM8975) += akm8975/
obj-$(CONFIG_SENSORS_MMA8452) += mma8452/
obj-$(CONFIG_SENSORS_AL3006)  += al3006/
obj-$(CONFIG_SENSORS_TMD2771) += tmd2771/
obj-$(CONFIG_SENSORS_LTR558)  += ltr558/
obj-$(CONFIG_SENSORS_BMM050)  += bmc050/
obj-$(CONFIG_SENSORS_LIS3DH)  += lis3dh/
obj-$(CONFIG_SENSORS_LSM303D) += lsm303d/
